### ISSUE TITLE
Extended sequences

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIMeasurements.jl#22]
I would like to propose a more elaborate mechanism for defining sequences.

Background:
Fully electric scanners and spectrometers often have rather simple sequences. Oftentimes it is not more than Tune->Empty measurement->Sample in/Move while acquiring data->Stop and sample out. But even with this case we can for example think of a bolus that is administered every x seconds. Other systems like INSPECT by Ankit require user  interaction at specific times for e.g. adding chemicals. Some things also take place in parallel to others like acquisition and robot movement. All this can be specified in a (acyclic) directed graph and executed stepwise.

It therefore would be awesome to structure the interactions of all devices including the DAQ around such sequences. As a specification I could think of the following:

We differentiate between STEPS and CONDITIONS. STEPS have a unique, human readable ID that identifies it and can be used for defining one or more consecutive STEPS. Predecessors can be determined by the graph structure. Every step should have a human readable description of what it does.  Every STEP has one or more ACTIONS associated with it. ACTIONS define calls to specific functions of a device. Since we need to know which specific device to use, every device must also have a unique, human readable ID. Every STEP defines a start CONDITION and a stop CONDITION.

A CONDITION might be for example 
- Always
- Timer
- User interaction 
- Interrupt from a device 
- Number of Periods read
- Finishing of multiple steps

By this, we should be able to define all the different systems in a standardized way.

Ideally, we would build a GUI in which the user can build a specific sequence for a given scanner. Since sequences are specific for a scanner, we should store the together. This might happen in a plain folder or a repository under version control that can be set-up by each group individually.

Implementation proposal:
STEPS are defined as a concrete type containing the aforementioned details. ACTIONS are set-up by are tuples of methods and parameter with the implicit contract that the first argument is always a concrete device data type. All ACTIONS that are allowed for a device can be retrieved by a @mustimplement actions(device::DeviceType, ...) function. The sequence is then a vector of STEPS which are evaluated in a graph like fashion. STEPS that should run in parallel are are executed asynchronously.

Open questions from my side:
- Should we have conditional branching of steps?
- Should cycles be allowed (of course with a loop counter)?
- How to deal with exact timings e.g. focus field 

I could implement a first go but I would like to have some discussion beforehand in order to not go awry.

**Comment by tknopp** [comment]
Yeah you have identified a very important point where `MPIMeasurements` is currently lacking a concept. This has been on my long turn TODO list and I would be happy if we could push this. My feeling is that we need a meeting to design this effectively. Here is a random list of thoughts:
1. What you describe here is called in ParaVision a `protocol`. So in that sense we have two different concepts: 1. synchronous this which I call `sequence` and 2. asynchronous actions I call `protocol`. We can bikeshed the names but I stay within this terminology within this post.
1. One crucial question is whether it makes sense to merge this two concepts or not. My feeling is that we should not merge them. A `sequence` is something which is very tightly coupled with the DAQ hardware while the `protocol` is more high-level
1. One thing where both concepts are clashing somewhat is the system matrix acquisition. If it is made asynchronously it would be natural to do this with a protocol. If done with an MPS with offset fields, the steps would usually be made within a sequence.
1. I think if we go this route we should define 2-3 realistic application scenarios an look that they are fully covered. In my opinion the framework should be powerful enough to be capable of doing a system matrix acquisition, which is not trivial. Good thing is that you can prototype this with `DummyDAQ` and `DummyRobot`
1. > Should we have conditional branching of steps?     
  I would say no because it increases the complexity of everything dramatically
1. > Should cycles be allowed (of course with a loop counter)?
  I am not fully sure: What we need is the possibility of looping over certain parameters, such aus the robot position.
1. > How to deal with exact timings e.g. focus field
  My feeling is that this is most easily done by differentiating between `sequence` and `protocol`.
1. Regarding the implementation we could also start thinking from the file format side: i.e. how to we want theses protocols to be serialized. 
1. We also need to think about how to store the data into an MDF. This is also not trivial. System matrices are usually stored within a single MDF but I fear that this framework will be to general to allow this. So its worth looking at the MDF specification to look what is possible.

**Comment by jonschumacher** [comment]
I like the split between protocols and sequences. A sequence can be a tight description of all magnetic fields with their respective signal type, frequency, amplitude and phase. All other stuff can be described within the protocol, which has no requirement for exact timings. I have to  think about how to deal with the combination of mechanical rotation and electromagnetic fields in Kolibri within this setup. I will try to compile a list of specific use cases that would be interesting to integrate.

**Comment by jonschumacher** [comment]
I implemented a first go on an abstract version but I have several open questions.
- Shouldn‘t the abstract types for the devices be defined in the respective files also defining the methods that must be implemented by the concrete implementations? Should all abstract device types be a subtype of e.g. AbstractDevice? Should DAQ be special or is it just another device?
- How should we deal with multiple devices of the same type e.g. multiple temperature sensors both implementation- and configuration-wise? I would use TOML subtables and unique IDs for each device.

I guess some answers to these questions might require a larger restructuring of code and could be discussed in our meeting in the middle of April.

**Comment by hofmannmartin** [comment]
If we think about things like bolus injection, or parallel running measurements of heart beat or temperature, we also need a way to deal with timing uncertainties. Often times the timing will likely be eyeballed. Maybe even unknown, before data inspection.

I agree that a meeting would certainly help.
