### ISSUE TITLE
Set upper bound to RP chunk size to prevent timeouts 

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIMeasurements.jl#39]
For long sequences the acquisition with the RP fails due to chunk lengths larger than the 5 second timeout.

**Comment by jonschumacher** [comment]
@nHackel : What’s our maximum concerning memory size?

**Comment by jonschumacher** [comment]
The offending line is actually https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/c91714f944a54938d9cc0214715254c0b6e2854a/src/Devices/DAQ/RedPitayaDAQ.jl#L318 or rather https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/c91714f944a54938d9cc0214715254c0b6e2854a/src/Devices/DAQ/RedPitayaDAQ.jl#L467. In conjunction with large lcm results from the old code in https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/5592a55e388c7aacadad44e3582936232f76a057/src/Sequences/Sequence.jl#L349 it results in a start write pointer much larger than the timeout time. One bad combination is 100 Hz plus 25 kHz at 32 decimation. Will solve by throwing an error if this time is too large.

**Comment by tknopp** [comment]
Are we talking about this?
```
https://github.com/tknopp/RedPitayaDAQServer/blob/master/src/client/julia/src/RedPitayaDAQServer.jl#L55
```
That 5 seconds is completely arbitrary and I introduced that because otherwise a socket read can last several minutes before the operating system kicks in and throws an error. So if your sequences are so long that the 5 seconds are reached we probably just want to change the timeout (adaptively before running the sequence)

**Comment by jonschumacher** [comment]
Yes, that is the timeout. We might make this configurable. Our sequences are not yet so long but they will be with the introduction of a translation in addition to the rotation. But in the original problem it was a mere configuration error.

**Comment by nHackel** [comment]
This only triggers a timeout with the "new" pipelined sample transmission, because here the server is responsible for checking the writepointer until the start is reached and not the client anymore. The latter is just waiting on the data socket for the pipeline to start.

I think I'll check if I can get the server and client in such a state that the client can query the writepointer of the server until the pipeline starts as a heartbeat and then we can still have a somewhat responsive timeout. 

Since the server can handle SCPI commands during transmission already, this might just be moving the code responsible for that up a few lines in the pipeline while-loop

**Comment by jonschumacher** [comment]
Sounds awesome! I just added a functionality to the client for changing the timeout period: https://github.com/tknopp/RedPitayaDAQServer/commit/cfa713ec2c1248c856603a0d91eb1b353ad885e0

**Comment by jonschumacher** [comment]
Should be fixed by https://github.com/tknopp/RedPitayaDAQServer/commit/c686b80db1e28052ef934b9c4ddfafa14b7c68c1.
